import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import FixedEmail from "@/components/Shared/FixedEmail/FixedEmail";
import FixedSocialMedia from "@/components/Shared/FixedSocialMedia/FixedSocialMedia";
import "../styles/globals.scss";
import RootProviders from "./RootProviders";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <RootProviders>
      <html lang="en">
        <body>
          <Header />
          <FixedSocialMedia />
          <FixedEmail />
          {children}
          <Footer />
        </body>
      </html>
    </RootProviders>
  );
}
